image: node:14.15.1

pipelines:
    branches:
        development:
            - step:
                  name: Build
                  caches:
                      - node
                  script:
                      - npm install && set GENERATE_SOURCEMAP=false && npm run build
                  artifacts:
                      - build/**

            - step:
                  name: Deployment
                  deployment: production
                  caches:
                      - node
                  script:
                      - pipe: atlassian/firebase-deploy:1.0.0
                        variables:
                            FIREBASE_TOKEN: $FIREBASE_TOKEN
                            PROJECT_ID: $FIREBASE_PROJECT
